jobs:
  get_target_env:
    name: "Get current environment"
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.set_result.outputs.target_env }}
    steps:
      - name: "Set env based on branch"
        shell: bash
        run: |
          echo "target_env=${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/stage' && 'stage' || 'develop' }}" >> $GITHUB_OUTPUT

  automated_job:
    name: "Test job"
    runs-on: ubuntu-latest
    needs: get_target_env
    environment:
      name: ${{ needs.get_target_env.outputs.target_env }}
    steps:
      - name: "Print env"
        shell: bash
        run: echo 'Using ${{ github.ref_name }}'
      - name: "Use var and secret from env"
        shell: bash
        run: echo '${{ vars.USERNAME }}:${{ secrets.PASSWORD}}'
